# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('post_time', models.DateField(auto_now_add=True)),
                ('modify_time', models.DateField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-post_time'],
            },
        ),
    ]
