# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170902_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('P', 'Python'), ('J', 'Java'), ('C', 'C'), ('O', 'Other')], max_length=30),
        ),
    ]
