# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170902_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=50, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('P', 'Python'), ('J', 'Java'), ('C', 'C'), ('O', 'Other')], max_length=30, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modify_time',
            field=models.DateField(auto_now=True, verbose_name='最近更新'),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_time',
            field=models.DateField(auto_now_add=True, verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
