# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170902_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最近更新'),
        ),
        migrations.AlterField(
            model_name='article',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发表时间'),
        ),
    ]
