# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170902_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
