# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170902_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['id'], 'verbose_name_plural': '用户'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(max_length=20, unique=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.PositiveSmallIntegerField(verbose_name='用户类型'),
        ),
    ]
